export interface CountryInfo {
  country: string;
  capital: string;
}

// Curated language(iso)→primary country for geo targeting. Approximate by design;
// only confident mappings are included. Keys match manifest language `code`.
export const LANGUAGE_COUNTRY: Record<string, CountryInfo> = {
  en: { country: 'United States', capital: 'Washington' },
  es: { country: 'Spain', capital: 'Madrid' },
  'es-LA': { country: 'Mexico', capital: 'Mexico City' },
  pt: { country: 'Portugal', capital: 'Lisbon' },
  'pt-BR': { country: 'Brazil', capital: 'Brasilia' },
  'pt-PT': { country: 'Portugal', capital: 'Lisbon' },
  fr: { country: 'France', capital: 'Paris' },
  br: { country: 'France', capital: 'Paris' },
  de: { country: 'Germany', capital: 'Berlin' },
  it: { country: 'Italy', capital: 'Rome' },
  nl: { country: 'Netherlands', capital: 'Amsterdam' },
  ru: { country: 'Russia', capital: 'Moscow' },
  uk: { country: 'Ukraine', capital: 'Kyiv' },
  pl: { country: 'Poland', capital: 'Warsaw' },
  cs: { country: 'Czech Republic', capital: 'Prague' },
  sk: { country: 'Slovakia', capital: 'Bratislava' },
  hu: { country: 'Hungary', capital: 'Budapest' },
  ro: { country: 'Romania', capital: 'Bucharest' },
  bg: { country: 'Bulgaria', capital: 'Sofia' },
  el: { country: 'Greece', capital: 'Athens' },
  sv: { country: 'Sweden', capital: 'Stockholm' },
  no: { country: 'Norway', capital: 'Oslo' },
  da: { country: 'Denmark', capital: 'Copenhagen' },
  fi: { country: 'Finland', capital: 'Helsinki' },
  is: { country: 'Iceland', capital: 'Reykjavik' },
  ca: { country: 'Spain', capital: 'Barcelona' },
  hr: { country: 'Croatia', capital: 'Zagreb' },
  sl: { country: 'Slovenia', capital: 'Ljubljana' },
  sq: { country: 'Albania', capital: 'Tirana' },
  mk: { country: 'North Macedonia', capital: 'Skopje' },
  lt: { country: 'Lithuania', capital: 'Vilnius' },
  lv: { country: 'Latvia', capital: 'Riga' },
  be: { country: 'Belarus', capital: 'Minsk' },
  cy: { country: 'United Kingdom', capital: 'Cardiff' },
  tr: { country: 'Turkey', capital: 'Istanbul' },
  ar: { country: 'Egypt', capital: 'Cairo' },
  fa: { country: 'Iran', capital: 'Tehran' },
  he: { country: 'Israel', capital: 'Jerusalem' },
  hi: { country: 'India', capital: 'New Delhi' },
  ta: { country: 'India', capital: 'Chennai' },
  te: { country: 'India', capital: 'Hyderabad' },
  ml: { country: 'India', capital: 'Kochi' },
  ur: { country: 'Pakistan', capital: 'Islamabad' },
  th: { country: 'Thailand', capital: 'Bangkok' },
  vi: { country: 'Vietnam', capital: 'Hanoi' },
  km: { country: 'Cambodia', capital: 'Phnom Penh' },
  my: { country: 'Myanmar', capital: 'Yangon' },
  'my-mm': { country: 'Myanmar', capital: 'Yangon' },
  id: { country: 'Indonesia', capital: 'Jakarta' },
  ms: { country: 'Malaysia', capital: 'Kuala Lumpur' },
  fl: { country: 'Philippines', capital: 'Manila' },
  ja: { country: 'Japan', capital: 'Tokyo' },
  kor: { country: 'South Korea', capital: 'Seoul' },
  ko: { country: 'South Korea', capital: 'Seoul' },
  'zh-CN': { country: 'China', capital: 'Beijing' },
  'zh-TW': { country: 'Taiwan', capital: 'Taipei' },
  'zh-HK': { country: 'Hong Kong', capital: 'Hong Kong' },
  mn: { country: 'Mongolia', capital: 'Ulaanbaatar' },
  ne: { country: 'Nepal', capital: 'Kathmandu' },
  'ne-NP': { country: 'Nepal', capital: 'Kathmandu' },
  hy: { country: 'Armenia', capital: 'Yerevan' },
  ka: { country: 'Georgia', capital: 'Tbilisi' },
  sw: { country: 'Kenya', capital: 'Nairobi' },
  zu: { country: 'South Africa', capital: 'Johannesburg' },
  af: { country: 'South Africa', capital: 'Cape Town' },
  sn: { country: 'Zimbabwe', capital: 'Harare' },
  yo: { country: 'Nigeria', capital: 'Lagos' },
  ig: { country: 'Nigeria', capital: 'Abuja' },
  ht: { country: 'Haiti', capital: 'Port-au-Prince' },
  ku: { country: 'Iraq', capital: 'Erbil' },
};
